### ISSUE TITLE
Agregar soporte para configuración

### ISSUE THREAD

**Issue by ariel17** [jmg/jcaching#1]
Agregar un módulo de configuración mediante archivos. Opciones de implementación:
- [XML](http://filmmakeriq.com/wp-content/uploads/2014/04/Spiderman-Crying.jpg)
- Properties
- [Apache Commons Configuration](http://commons.apache.org/proper/commons-configuration/userguide/user_guide.html)
- JSON
- ¿Otra?

Yo iría por Apache commons: esa biblioteca es excelente por la calidad de implementación de las herramientas.

**Comment by jmg** [comment]
Agregué una clase [Config](https://github.com/jmg/jcaching/blob/master/src/main/java/org/jcaching/config/Config.java) para implementar esto. Ahora el hashmap [ConfigValues](https://github.com/jmg/jcaching/blob/master/src/main/java/org/jcaching/config/Config.java#L40) tiene valores hardcodeados pero habría que moverlos al config file una vez que elijamos el formato a utilizar e implementemos el parser.

**Comment by jmg** [comment]
+1 Apache Commons Configuration con PropertiesConfiguration. De esa manera nos quedaría un .properties como los de [LOG4J](https://github.com/jmg/jcaching/blob/master/src/main/resources/log4j.properties).

-1 XML. Demasiado verboso innecesariamente.
