### ISSUE TITLE
Unidad de timeout

### ISSUE THREAD

**Issue by mszuchman** [jmg/jcaching#10]
milisegundos?

**Comment by jmg** [comment]
Sí, milisegundos está bien para mí

**Comment by ariel17** [comment]
Pero... ¿tan rápido la data puede llegar a estar invalidada? Yo creo que con segundos alcanza. Si tuviésemos que usar milisegundos como unidad es que estamos en otro escenario donde usar caché no es la mejor opción. Cuando usás caché estás asumiendo que vas a estar desfazado en el tiempo con lo que es la realidad; estás sacrificando velocidad de actualización de los datos en pos de mejor rendimieto.

**Comment by jmg** [comment]
@ariel17 Tenés razón, deberian ser segundos. No tiene mucho sentido invalidar un objeto en cache en 500 milisegundos.

**Comment by mszuchman** [comment]
Sisi, mala mía, quise decir segundos. Incluso en el código lo contemple como segundos.
