### ISSUE TITLE
Elegir motor de serialización

### ISSUE THREAD

**Issue by ariel17** [jmg/jcaching#2]
Tenemos que ponernos de acuerdo con la selección de la implementación de la serialización:
- [MsgPack](http://msgpack.org/)
- [Gson](https://code.google.com/p/google-gson/)
- [Serialización simple](http://javapostsforlearning.blogspot.com.ar/2013/03/serialization-in-java.html): no deberíamos implementar nada más.
- JSON
- Introspection
- ¿Otra?

Mi opinión es que deleguemos esta parte o usemos lo más simple posible.

**Comment by jmg** [comment]
+1 MsgPack
+1 Gson

Estoy de acuerdo que lo más simple es delegar esto al user. Pero me gustaría prestarle esta facilidad de auto-serialización de objetos. La idea sería dejar al user elegir si quiere serializar lo objetos el mismo, por ende, enviarnos un string, o bien, dejar que nuestro framework lo haga por él.
Un problema que surge con esto es que tanto el metodo GET como SET tienen que estar sobrecargados para aceptar, mínimamente, Object y String. Además, deberiamos guardar el tipo de dato del objeto que el usuario nos envíe, para poder devolverle lo que está en cache desserializado cuando el usuario llame al método GET.

**Comment by ariel17** [comment]
Me parece bien; es más, yo había entendido que la idea era esa :) dar soporte a cualquier clase que mande el usuario. La única restricción que el usuario va a tener es que las clases componentes de su objeto, en caso de que sea compuesto, deben ser serializables de algún modo (no puede tratar de cachear un objeto Connection por ej).

Con Gson lo podemos resolver bastante fácil: en la parte de _Serializing and deserializing generic types_ de la [documentación](https://sites.google.com/site/gson/gson-user-guide#TOC-Using-Gson) muestra como resolver inclusive el casteo contra tipos de datos genéricos.

Investigado este escenario con MsgPack vi que [no tiene bien resulto cómo el tema de clases genéricas y la comunidad aconseja usar Gson para estos casos](http://stackoverflow.com/a/18571017/1819550)... Así que yo mudo todos mis porotos a Gson :)

+2 Gson.

**Comment by ariel17** [comment]
¿Queda Gson entonces? Si no hay otras opiniones hasta la noche asumo que sí.

**Comment by jmg** [comment]
Gson está bien para mi
