### ISSUE TITLE
Soporte de carga de backend en la clase cliente

### ISSUE THREAD

**Issue by ariel17** [jmg/jcaching#3]
Este cliente no está contemplando distintas implementaciones. Deberíamos plantearnos un cliente más generico que soporte el cambio de backend en base a la configuración mediante class loader o un alias de clase + reset de la instancia de backend en momento de ejecución.

**Comment by jmg** [comment]
Debería existir una clase que haga la carga de la configuración del XML, JSON, etc y mediante class loader levante la clase correspondiente (una de las que implementan la interfaz CacheBackend) y la instancie. Está sería la interfaz de nuestro sistema con el usuario. Un único objeto o clase Cache.

**Comment by ariel17** [comment]
:+1:

**Comment by jmg** [comment]
Implementé una clase estática [Cache](https://github.com/jmg/jcaching/blob/master/src/main/java/org/jcaching/cache/Cache.java) para hacer de Facade con el sistema. Esta clase sería la interfaz con el usuario de nuestro sistema. La misma levanta el backend del [Config](https://github.com/jmg/jcaching/blob/master/src/main/java/org/jcaching/config/Config.java#L40). 

@ariel17 Decime que te parece. Está totalmente abierto a cambios. Pero este debería ser el lugar donde se va a decidir que backend se va a usar y no [CacheClient](https://github.com/jmg/jcaching/blob/master/src/main/java/org/jcaching/client/CacheClient.java). Esa clase es propia de la implementación del backend en memoria y no debería ser utilizada por otros backends.

También cambié la forma en la que hago los [tests](https://github.com/jmg/jcaching/blob/master/src/test/java/org/jcaching/backends/impl/MemoryProcessBackendTest.java#L22) para el backend en memoria. Ahora uso la Facade forzandole el backend en memoria.

**Comment by ariel17** [comment]
Perdón, recién veo este ticket :(

Me parece bien _salvo_ el nombre de la clase. Pensá que es nuestra puerta de entrada hacia los programadores (ya estamos participando en código de otros) y es nuestra oportunidad sino el deber de hacer resaltar el proyecto:
- `org.jcaching.client.JCachingClient`
- `org.jcaching.JCachingClient`
- `org.jcaching.JCaching` (esto es incluso mucho más genérico que lo anterior porque sería la clase más baja en el árbol. Acá podríamos poner cosas como `org.jcaching.JCaching.getConfig()`; quizás un `org.jcaching.JCaching.setConfig()`, `org.jcaching.JCaching.getClient()`...)

**Comment by jmg** [comment]
+1 `org.jcaching.JCaching`

No le agregaría el "Client" al final porque es un nombre que denota implementación (cliente-servidor). El usuario debería estar abstraído de esto. Con lo cual un método `org.jcaching.JCaching.getCache()` me parece mas apropiado. `setConfig` y `getConfig` suenan bien. Deberíamos implementarlos :)

**Comment by jmg** [comment]
@ariel17 cambie la interfaz de la clase [Cache](https://github.com/jmg/jcaching/blob/master/src/main/java/org/jcaching/cache/Cache.java) para que use Object tal como lo hablamos ayer. De paso adapte mi backend (ahora se llama SocketMemoryBackend) para que matchee esa interfaz. Lo que faltaría hacer es implementar la parte del Config usando lo que discutimos en #1
